### ISSUE TITLE
possibility of mischief with the CDK snippet

### ISSUE THREAD

**Issue by rosskarchner** [AndrewGuenther/fck-nat#1]
I might be wrong about this, but it seems like, if I created a public AMI that fits the pattern `fck-nat-*-arm64-ebs`, with a higher version number, it would supersede the "official" fck-nat image when users run your example CDK code:

```
const vpc = new Vpc(this, 'vpc', {
    natGatewayProvider: new NatInstanceProvider({
        instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
        machineImage: new LookupMachineImage({
            name: 'fck-nat-*-arm64-ebs'
        })
    }),
});
```

**Comment by AndrewGuenther** [comment]
You're right, account id needs to be added in there. Good catch.

**Comment by AndrewGuenther** [comment]
Thanks again for the catch @rosskarchner!
