### ISSUE TITLE
Docs: Website docs inconsistent with latest repo docs

### ISSUE THREAD

**Issue by bml1g12** [AndrewGuenther/fck-nat#100]
https://github.com/AndrewGuenther/fck-nat/pull/73
https://github.com/AndrewGuenther/fck-nat/pull/86

It seems these changes to docs are not yet reflected on https://fck-nat.dev/v1.3.0/deploying/#cloudformation and the website gives no indication the docs are deprecated. I ran into this as I tried deploying the cloudformation template on website which are broken and fixed in those PRs

**Comment by AndrewGuenther** [comment]
Docs are deployed and this is now fixed!
