### ISSUE TITLE
Use an EIP to create a static IP address for the NAT Gateway

### ISSUE THREAD

**Issue by rcoundon** [AndrewGuenther/fck-nat#14]
Thanks for your work on this project, it looks ideal for our needs and sorely needed generally. I apologise if this isn't the ideal place to ask this question, I'm more than happy to be pointed to some standard AWS documentation too.

What I'd like to do is, using CDK, create an Elastic IP Address that can be used by the fck-nat NatInstanceProvider so that it can act as a static IP address for traffic to external (to AWS) APIs (ultimately from lambda functions) but I can't work out how the various pieces NatInstanceProvider, CfnEIP, CfnEIPAssociation etc fit together. 

Any pointers would be greatly appreciated. Thank you

**Comment by AndrewGuenther** [comment]
Can you tell me a little more about your use case? You just want the NAT instance to be visible on the public internet via EIP?

**Comment by AndrewGuenther** [comment]
I'm actually working on a CDK construct to wrap `fck-nat` over at https://github.com/AndrewGuenther/cdk-fck-nat. I think this issue would be best placed there. It isn't quite ready for release, but I'll take this into consideration once I understand your use case better.

**Comment by rcoundon** [comment]
Thanks for getting back to me. The use case is that I want to be able to route lambda traffic (3rd party API calls) to the internet via a known, static IP address so that it can be whitelisted by the customer that hosts the 3rd party API.

**Comment by AndrewGuenther** [comment]
Ah, I gotcha. So if you want a quick and dirty that doesn't require HA mode, you can use [CDK's default `NatInstaceProvider`][1] and pass the fck-nat AMI ID to the `machineImage` parameter. This will wire up a single-node NAT instance for you that works out of the box. Here's an example (in Python):

```python
        nat_gateway_provider = ec2.NatInstanceProvider(
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE4_GRAVITON, ec2.InstanceSize.MICRO),
            machine_image=ec2.MachineImage.generic_linux(ami_map={
                # The AMI id is hardcoded here, but you can do it as a search instead if you want so you always get the latest
                "us-west-2": "ami-086528c53de1ad587"
            })
        )
```

Now `nat_gateway_provider` has a `configuredGateways` property which contains the instance id of the NAT instance. You can take that string and pass it to a [`CfnEipAssociation` construct.][2]

This all gets a lot more complicated in HA mode since an autoscaling group is involved...

[1]: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.NatInstanceProvider.html
[2]: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.CfnEIPAssociation.html

**Comment by rcoundon** [comment]
That's fantastic, I can probably do without HA mode for now anyway. I'll give that a go, thank you!

**Comment by AndrewGuenther** [comment]
I'm going to go ahead and close this out since you've got some options for a path forward. Feel free to reach out if you need help with anything else!

**Comment by rcoundon** [comment]
No problem, I'll likely be giving this a go in the week or so when things settle down. Thank you

**Comment by TehNrd** [comment]
@rcoundon If you got this working can you add the CDK code? 

Having a static outbound IP Addresses is the #1 reason I use NAT Gateways, so while this issue is closed, I'd still love to see it eventually added to the package.

**Comment by rcoundon** [comment]
> @rcoundon If you got this working can you add the CDK code?
> 
> Having static outbound IP Addresses is the number 1 reason I use NAT Gateways, so while this issue is closed, I'd still love to see it eventually added to the package.

I haven't gotten around to it yet, the customer requirement has been pushed out so I've been focussing on other stuff for now. As soon as it becomes a priority and I have it working, I'll share here

**Comment by AndrewGuenther** [comment]
@TehNrd are you specifically asking for support for an EIP in high availability mode? Use of an EIP is supported in single node setups already, it's just outside the responsibility of fck-nat itself to configure that EIP which is why I referred back to CDK.

That said, I can make some improvements to the documentation to better explain how to set up an EIP in single-node mode.

**Comment by rcoundon** [comment]
> @TehNrd are you specifically asking for support for an EIP in high availability mode? Use of an EIP is supported in single node setups already, it's just outside the responsibility of fck-nat itself to configure that EIP which is why I referred back to CDK.
> 
> That said, I can make some improvements to the documentation to better explain how to set up an EIP in single-node mode.

For me, it's really both. Improved docs on single-node mode setup would be cool and I'm likely to need to use a static EIP in both modes

**Comment by TehNrd** [comment]
A single node would be sufficient, and docs with an example would be helpful. How to in CDK, create an EIP and then pass this to the fck cdk config. I think it is just this section that needs an example of out to pass in the EIP:

```
const vpc = new Vpc(this, 'vpc', {
    natGatewayProvider: new NatInstanceProvider({
        instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
        machineImage: new LookupMachineImage({
            name: 'fck-nat-amzn2-*-arm64-ebs',
            owners: ['568608671756'],
        })
    }),
});
```

HA would be a bonus, but I can see how HA would be a challenge. Even though autoscaling group size may be set to a max of 1 you can sometimes get more than one EC2 as the group scales up and down. In these cases, we'd need to pass in an array of EIP it could pull from. Again, not a super high priority, but long-term nice to have.

And loving this solution, thank you so much for creating it. It's great for small projects that need static outbound IP addresses.
