### ISSUE TITLE
Add the possibility of building NAT instance images on the fly

### ISSUE THREAD

**Issue by moltar** [AndrewGuenther/fck-nat#15]
I don't feel comfortable using pre-built images, as they could in theory be tampered with.

Would be great to be able to use a standard Amazon Linux image, and then do the setup through user scripts.

**Comment by AndrewGuenther** [comment]
There are currently two supported options for this:
1. You can build your own AMI using Packer. `make all-amis` will build an AMI and publish it to your account
2. If you don't want to build an AMI at all, there is an `rpm` available in the releases which you can install yourself.

**Comment by AndrewGuenther** [comment]
Docs for this are available in the following locations:

https://fck-nat.dev/#building-your-own-fck-nat-ami
https://fck-nat.dev/#installing-fck-nat-from-the-rpm

Resolving. Let me know if you have any other questions!

**Comment by moltar** [comment]
Thanks, Andrew!

RPM sounds like good middle ground.
