### ISSUE TITLE
Report additional metrics from fck-nat

### ISSUE THREAD

**Issue by AndrewGuenther** [AndrewGuenther/fck-nat#16]
One goal for fck-nat is to provide as close as possible metric parity with Managed NAT Gateway. The list of supported metrics for Managed NAT Gateway can be found here: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html

**Comment by Devesh-N** [comment]
+1

**Comment by jonaswashe** [comment]
+1

**Comment by mecsys** [comment]
+1
