### ISSUE TITLE
Amazon Linux 2023 support?

### ISSUE THREAD

**Issue by kyontan** [AndrewGuenther/fck-nat#18]
Hi,

I want to know is there a plan for supporting Amazon Linux 2022?

There's EoL for Amazon Linux 2 at 2024-06-30 (extended from 2023-06-30), it's not so nearly, but the post AL2 is already released.
I know it can be built by manually creating AMI, but I'd be happy if public AMI is released.

- https://aws.amazon.com/amazon-linux-2/faqs/
- https://aws.amazon.com/linux/amazon-linux-2022/

**Comment by AndrewGuenther** [comment]
It's on my radar, but I'm not going to commit to a timeline at the moment. Contributions are always welcome.

**Comment by AndrewGuenther** [comment]
Going to bring this in with live patching support.

**Comment by souravjamwal77** [comment]
@AndrewGuenther I can help.

**Comment by k5njm** [comment]
@AndrewGuenther Thanks for the great project, super useful for small demo environments (especially when paying out of pocket).

The upgrade to AL2023 should also bring in support for Wireguard, thanks to a much newer kernel. This is great for those that are using the instance as a bastion/vpn as well.

**Comment by alekc** [comment]
> The upgrade to AL2023 should also bring in support for Wireguard, thanks to a much newer kernel. This is great for those that are using the instance as a bastion/vpn as well.

Just FIY: you can already use wireguard on AL2 in kernel mode, as long as you install the latest 5.x kernel

**Comment by RaJiska** [comment]
Perhaps this feature can can be added as part of the v2 release.

**Comment by AndrewGuenther** [comment]
@RaJiska I'm hoping to do this before v2. Ideally in the next release.
