### ISSUE TITLE
Enable kernel livepatching in base AMI

### ISSUE THREAD

**Issue by AndrewGuenther** [AndrewGuenther/fck-nat#19]
If kernel live patching is enabled in the base AMI, it will ensure that if Patch Manager runs the standard AL2 baseline that kernel patches are applied.

Execution of patch baselines is out of scope for this project, but will be added to the cdk-fck-nat construct.

**Comment by AustinAMeyer** [comment]
Just a note if you want to update the documentation for Cloudformation you could add the below statement to install patches in the userdata and also install SSM for automated patching in the future.

`FckNatAsgLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-05b6d5a2e26f13c93
      InstanceType: t4g.nano
      KeyName: !Sub ${KeyName}
      IamInstanceProfile:
        Ref: FckNatAsgInstanceProfile
      SecurityGroups:
        - Fn::GetAtt:
            - NatSecurityGroup
            - GroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_arm64/amazon-ssm-agent.rpm
          echo "eni_id=${FckNatInterface}" >> /etc/fck-nat.conf
          service fck-nat restart
    DependsOn:
      - NatRole`
