### ISSUE TITLE
per GB (data transfer) rates assumptions

### ISSUE THREAD

**Issue by zerog2k** [AndrewGuenther/fck-nat#20]
First of all let me say, big thanks for putting this together, as AWS NATGWs are one of those things (like Cloudwatch) which for some reason AWS really overcharges for. (I guess it's because almost everyone needs it, and short of a project like this, there aren't much in the way of alternatives.) While I'm not sure we'd consider using this for our production accounts, this might make alot of sense for limiting costs in development/non-productions accounts/situations.

On your introduction page, it's stated that the "Per GB rates" (i.e. ec2 data transfer) for `fck-nat` per GB are $0.00.
I think this deserves an "asterisk", as it isn't always exactly true. All NAT activity is two way, although it's probably generally the case that it's going to be overwhelmingly heavily "download" (i.e. "Data Transfer IN To Amazon EC2 From Internet") which _is_ "free". However, there is always still _some_ traffic (http requests, TCP, acks, etc), and then certain types of access patterns (uploading traffic to other sites/clouds/on-prem, etc) which _may_ run into the "upload" (i.e. "Data Transfer OUT From Amazon EC2 To Internet") use case. For small/light use cases, this might be satisfied by the "First 100GB free", but then it's very possible to get into the $0.09/GB for up to first 10TB/month of transfer.

Per EC2 pricing page, for common US regions (i.e. Oregon, Ohio, Virginia):

![image](https://user-images.githubusercontent.com/3943170/197547999-c8bbafb7-3db4-49c9-91d4-a3b3d79e9810.png)

ref: https://aws.amazon.com/ec2/pricing/on-demand/

Not trying to nitpick, but just trying to make sure folks going in are fully aware, so they can work up an accurate cost comparison for their situation.

Additionally, while it's only tangentially related to nat, maybe it's worth at least pointing out that folks who are looking into managed natgw alternatives (due to costs), should likely be using VPC endpoints for their common AWS services, e.g. S3. For some use cases, not having things like S3 endpoints could be a major cost driver on natgws.
Ref: https://aws.amazon.com/blogs/architecture/reduce-cost-and-increase-security-with-amazon-vpc-endpoints/

Again, thanks for this!

**Comment by AndrewGuenther** [comment]
I think the comparison in the Introduction is fair. It's a comparison of per GB processing fees charged by NAT Gateway which is in addition to the standard per GB data transfer rates. Since both NATGW and fck-nat are subject to those charges, it's immaterial to a cost comparison.

As for mention of VPC endpoints, I think that's a good suggestion, especially S3 endpoints since they're free. I'm generally not a huge fan of VPC endpoints since 9 times out of 10 you're going to need so many of them that the costs get close to NATGW anyway, but it wouldn't hurt to mention to make people aware.

**Comment by zerog2k** [comment]
Ok that makes sense. Thanks for clearing it up.
