### ISSUE TITLE
Support for M6in

### ISSUE THREAD

**Issue by jacob-aegis** [AndrewGuenther/fck-nat#23]
m6in.32xlarge can support up to 200 Gbps.  My application only needs the NAT for inbound traffic.  That being the case, is it feasible to use fck-nat with a m6in.32xlarge and get 200 Gbps inbound?  I can see you've noted 5 Gbps for egress, but I don't see a limit for ingress.

**Comment by AndrewGuenther** [comment]
[From the docs:](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-network-bandwidth.html)

> To other Regions, an internet gateway, Direct Connect, or local gateways (LGW) – Traffic can utilize up to 50% of the network bandwidth available to a [current generation instance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#current-gen-instances) with a minimum of 32 vCPUs. Bandwidth for a current generation instance with less than 32 vCPUs is limited to 5 Gbps.

So it would be "up to 50%" of 200Gbps, so a max of 100Gbps. AWS doesn't provide any further guarantees.

**Comment by jacob-aegis** [comment]
Thanks for the quick response.  Current need is nowhere near 200 Gbps, but good to know that the real theoretical limit is up to 100 Gbps.
