### ISSUE TITLE
The provided CloudFormation template fails when you try to launch the ASG from a different region from the AMI location

### ISSUE THREAD

**Issue by cr0fters** [AndrewGuenther/fck-nat#29]
I get the following CloudFormation error when I've tried to launch from within the London region:

`Resource handler returned message: "AMI ami-05b6d5a2e26f13c93 is invalid: The image id '[ami-05b6d5a2e26f13c93]' does not exist (Service: AutoScaling, Status Code: 400, Request ID: 3e011264-ee7c-4808-93b7-23155c08181f)" (RequestToken: 09753d0b-5eae-610d-efce-95f0802b9c17, HandlerErrorCode: InvalidRequest)`

Could you possibly copy the AMI into a few different popular regions and add a CloudFormation mapping to point to the regional AMI? I've tried copying it but get the error `Failed to copy ami-05b6d5a2e26f13c93 You do not have permission to access the storage of this ami`

**Comment by cr0fters** [comment]
I've temporarily got around this by launching an instance from the AMI, creating an image from it, then copying the image into the London region and referencing that AMI ID.

**Comment by AndrewGuenther** [comment]
The fck-nat AMI is published to all non-opt-in regions. You can find your region's AMI ID with the following command:

```
aws ec2 describe-images --owners 568608671756 --filters 'Name=name,Values=fck-nat-amzn2-*'
```

**Comment by cr0fters** [comment]
Thanks, and apologies, I missed this in the docs :)

**Comment by bpottier** [comment]
Unless I am missing something, there does not seem to be an image available in us-east-1.

**Comment by AndrewGuenther** [comment]
@bpottier you are missing something 🙂

```
aws ec2 --region=us-east-1 describe-images --owners 568608671756 --filters 'Name=name,Values=fck-nat-amzn2-*'
```

This command will list all AMIs in us-east-1

**Comment by bpottier** [comment]
> @bpottier you are missing something 🙂
> 
> ```
> aws ec2 --region=us-east-1 describe-images --owners 568608671756 --filters 'Name=name,Values=fck-nat-amzn2-*'
> ```
> 
> This command will list all AMIs in us-east-1

Yes I am. Sorry. I was hitting some weird CDK issue where the region wasn't resolving and it led me here incorrectly. Thank you!
