### ISSUE TITLE
Publish example CloudFormation snippets for configuring fck-nat

### ISSUE THREAD

**Issue by AndrewGuenther** [AndrewGuenther/fck-nat#3]

**Comment by supriyo-biswas** [comment]
A little while ago I wrote this Cloudformation template to make use of fck-nat in a VPC. Maybe it can be included?
https://gist.github.com/supriyo-biswas/33043bea2237f9579b1e81f712cf25f6

**Comment by AndrewGuenther** [comment]
Excellent. This will definitely save me some time. Thanks!

**Comment by AndrewGuenther** [comment]
@supriyo-biswas Thanks again for those snippets! I've integrated a subset of your template into the docs here: https://fck-nat.dev/deploying/#cloudformation
