### ISSUE TITLE
Cloudformation deploy procedure routetable update 

### ISSUE THREAD

**Issue by monkut** [AndrewGuenther/fck-nat#30]
> Steps to deploy:

> 1. Paste your VPC ID, public subnet ID, and CIDR block into the parameters.
> 2. Ensure that your public subnet has Enable auto-assign public IPv4 address turned on. This can be found in the Console at VPC > > Subnets > Edit subnet settings > Auto-assign IP settings.
> 3. Deploy with cloudformation aws cloudformation deploy --force-upload --template-file template.yml --stack-name FckNat
> 4. Add the default route to your route table on the subnet. It is best to do this manually so you can do a seamless cut over from your > existing nat gateway. Go to VPC > Route Tables > PUblic route table > Routes > Edit Routes Add a 0.0.0.0/0 route pointing to the network interface.

Maybe my configuration is different, but in my case, if you remove the internet-gateway route from the public route table you will no longer have access to the internet.

I believe this should be changed from _Public route table_ to _Private route table_:

> Go to VPC > Route Tables > PUblic route table > Routes > Edit Routes Add a 0.0.0.0/0 route pointing to the network interface.

--> 

> Go to VPC > Route Tables > **Private** route table > Routes > Edit Routes Add a 0.0.0.0/0 route pointing to the network interface of the FCK-NAT instance.

**Comment by AndrewGuenther** [comment]
Yep, you're right, it should be private route table

**Comment by AndrewGuenther** [comment]
@monkut Can you confirm that #31 resolves this issue? Is there anywhere else in the docs where public/private need to be updated?
