### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by filipend0** [AndrewGuenther/fck-nat#34]
Hello, nice repo, is this still working?
I have tried deploying your solution into existing cloudformation solution with VPC containing 2 VPC subnets, few lambda functions and EC2 instances which already has public IP.
After deploying your solution I can not access public internet from lambdas(same as before), and also can not ssh into existing EC2 instances which was before possible. 
I can only ssh into nat ec2 instance.

I had found, that new amazon linux 2 had some problem with iptables, I could not even list with command "**iptables -t nat -L**"
but it was probably solved by adding 
**sudo modprobe ip_tables
echo 'ip_tables' >> /etc/modules**
into UserData script.

I have also tried using custom interface as you did in example https://fck-nat.dev/deploying/
and also tried default vpc route with both NetworkInterfaceId or InstanceId but with same effect.

So actually I m out of ideas what could be wrong.

**Comment by AndrewGuenther** [comment]
Yes, this repository still works. Can you tell me a bit more about how you're deploying fck-nat? Are you using one of the AMIs or installing the rpm directly?

**Comment by patrickdk77** [comment]
I am using, aws ssm get-parameters --names /aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs --query 'Parameters[0].[Value]' --output text
launching into a t4 and the launchdata installs the rpm, I haven't had any issues.
I am using a dedicated netowork interface for mine.

**Comment by filipend0** [comment]
Hmm. Thats strange because somehow, after few hours it is working, but I changed nothing since I wrote here... 
Thanks.
