### ISSUE TITLE
[NOTAISSUE] FCK-NAT on Kubernetes

### ISSUE THREAD

**Issue by Devesh-N** [AndrewGuenther/fck-nat#38]
Hey @AndrewGuenther it's me, Dev-n-22 from r/aws! I saw your comment on my post a while ago and I used FCK-NAT and it was excellent. I used the AWS GUI console for that. I also saw that there was H.A for it, but I am a noob in AWS and I don't want to use a "Autoscaling group". I decided that the next best option was to use EKS! But I don't see any documentation for deploying FCK-NAT using kubectl. So I wanted to know if there is any way I can somehow do it.

**Comment by AndrewGuenther** [comment]
There is not a way to deploy fck-nat on Kubernetes and there are not currently any plans to support fck-nat on Kubernetes. I don't even think you can run a NAT host with k8s given how networking gets set up there?

**Comment by Devesh-N** [comment]
> There is not a way to deploy fck-nat on Kubernetes and there are not currently any plans to support fck-nat on Kubernetes. I don't even think you can run a NAT host with k8s given how networking gets set up there?

Okay @AndrewGuenther I am a noob in kubernetes. Also I am having zero idea in making the nat gateway a high availability thing and am getting confused. A little new to AWS too
