### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by RaJiska** [AndrewGuenther/fck-nat#54]
Adding this issue as a suggestion to add versioning to documentation. Currently a few changes that are pushed are added to the documentation and yet are not actually published in the latest version.

A solution could be to versionise the documentation and have an "unreleased" version or something in the documentation containing the latest changes. This would reduce the confusion with people trying to use the project and not understanding why some features are not available when using the latest AMI.

**Comment by AndrewGuenther** [comment]
This was a pretty quick and easy thing to add. All done.
