### ISSUE TITLE
Package fck-nat as a .deb and .rpm

### ISSUE THREAD

**Issue by AndrewGuenther** [AndrewGuenther/fck-nat#6]
Depends on #5

**Comment by shakalandy** [comment]
Do you plan to use FPM [1] for building the packages?
FPM could built both formats.

[1]: https://github.com/jordansissel/fpm

**Comment by AndrewGuenther** [comment]
@shakalandy Begrudgingly, yes, I'll probably use FPM. FPM doesn't support packaging systemd services in both formats, but it can be hacked together. FPM is a massive pain to use (although less pain than the alternatives), but hopefully this is a "write once, never touch again" situation (famous last words).

**Comment by AndrewGuenther** [comment]
Resolved by e99fa77199378b820e9d0d5dfc88deb24abd3d08
