### ISSUE TITLE
Bandwidth is dependent on instance size

### ISSUE THREAD

**Issue by hrist0stoichev** [AndrewGuenther/fck-nat#60]
The documentation suggests that `fck-nat` supports 5Gbps bandwidth on **any** EC2 instance. This however turns out to not be exactly true.

Here are some direct quotes from the [Amazon EC2 instance network bandwidth documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-network-bandwidth.html).
```
[Internet gateway] bandwidth for a current generation instance with less than 32 vCPUs is limited to 5 Gbps.
```

```
Typically, instances with 16 vCPUs or fewer (size 4xlarge and smaller) are documented as having "up to" a specified bandwidth; for example, "up to 10 Gbps". These instances have a baseline bandwidth. To meet additional demand, they can use a network I/O credit mechanism to burst beyond their baseline bandwidth. Instances can use burst bandwidth for a limited time, typically from 5 to 60 minutes, depending on the instance size.

An instance receives the maximum number of network I/O credits at launch. If the instance exhausts its network I/O credits, it returns to its baseline bandwidth. A running instance earns network I/O credits whenever it uses less network bandwidth than its baseline bandwidth. A stopped instance does not earn network I/O credits. Instance burst is on a best effort basis, even when the instance has credits available, as burst bandwidth is a shared resource.
```

This basically says that although there is a 5Gbps limitation, smaller instances have a much lower baseline bandwidth. [This page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/general-purpose-instances.html#general-purpose-network-performance) shows that `t4g.nano` instances have `0.032 Gbps` baseline bandwidth and can burst to `5 Gbps`. Unfortunately, I cannot find any documentation that gives more details about the "network I/O credits", i.e. how they are accumulated, how many credits are assigned to each instance size, how to monitor them, etc. For example, `t4g.micro` has twice the baseline bandwidth as `t4g.nano` but is the same true for "network I/O credits"? Does it have twice the credits? Do they replenish twice as fast? No idea...

I created this issue because I think the `fck-nat` documentation needs to take this into account. It should be made clear that bandwidth is dependent upon instance size and using the smallest instance, `t4g.nano`, would not deliver 5Gbps 24/7. 

After comparing instance types, here are the ones that make most sense
- t4g.nano - 0.032 Gbps baseline bandwidth for ~$3 per month
- t4g.micro - 0.064 Gbps baseline bandwidth for ~$6 per month
- t4g.small - 0.128 Gbps baseline bandwidth for ~$12 per month
- c7gn.medium - 3.125 Gbps baseline bandwidth for ~46 per month

**Comment by AndrewGuenther** [comment]
I'll add a page to the docs that goes into this. There's a lot of weird sharp edges when it comes to EC2 and bandwidth and would be good to consolidate them all in one place in the docs.

**Comment by hrist0stoichev** [comment]
On a side note, instead of scaling vertically (by increasing instance size), would it be possible to scale horizontally by adding multiple `fck-nat` instances and a load balancer in front of them? Then the route table will not route directly to the instance using the ENI but rather to the load-balancer which in turn will route to some of the instances.

**Comment by bqiang-stackadapt** [comment]
Also curious how would you scale up horizontally. Does not sound very easy... Thanks!

**Comment by AndrewGuenther** [comment]
Unfortunately no, you can't perform NAT using a load balancer so horizontal scaling is not possible.

**Comment by hrist0stoichev** [comment]
Can you elaborate? What prevents performing NAT using a load balancer?

**Comment by hrist0stoichev** [comment]
> Can you elaborate? What prevents performing NAT using a load balancer?

I still haven't looked into that but just wanted to point out that slight horizontal scaling (at least 3x) is possible by deploying a fck-nat instance in each AZ which also has the nice side effect of increased availability.

**Comment by AndrewGuenther** [comment]
> Can you elaborate? What prevents performing NAT using a load balancer?

NAT is a layer 3 service and NLBs work at layer 4. Gateway Load Balancers work at layer 3 and are technically an option but bring their own additional associated costs and are quite a bit more complex.

>I still haven't looked into that but just wanted to point out that slight horizontal scaling (at least 3x) is possible by deploying a fck-nat instance in each AZ which also has the nice side effect of increased availability.

That's not horizonal scaling. Horizontal scaling implies there is some form of load balancing. Multi-az does improve resiliency though and is already supported by fck-nat today.

**Comment by AndrewGuenther** [comment]
https://fck-nat.dev/develop/choosing_an_instance_size/

Docs page on instance sizes is now available here.
