### ISSUE TITLE
Should "enhanced networking" be enabled

### ISSUE THREAD

**Issue by hrist0stoichev** [AndrewGuenther/fck-nat#61]
I read about enhanced networking in AWS documentation and wonder whether it should be enabled on my `fck-nat` instance. Since there is no information about this in the documentation, can someone give more details about it?

**Comment by AndrewGuenther** [comment]
Enhanced networking is already enabled when using Amazon Linux distributions, so no work to be done here.

**Comment by hrist0stoichev** [comment]
Thanks!
