### ISSUE TITLE
Install SSM in AMI

### ISSUE THREAD

**Issue by AndrewGuenther** [AndrewGuenther/fck-nat#63]
Given that SSM provides a whole host of useful functionality, I'm walking back my previous stance that it should be installed in user data. Installing as user data slows down boot up times and we definitely don't want that here.

This was somewhat pork barreled into #47 so creating a dedicated issue for it.

**Comment by patrickdk77** [comment]
I'm confused about adding SSM, SSM has been installed by default for a long time now, the only thing that needs to be done to use it is to attach a proper permission ec2role to the instance.

**Comment by AndrewGuenther** [comment]
@patrickdk77 SSM is not installed in the minimal AMI that we use as a base

**Comment by patrickdk77** [comment]
ah, I'm not using the minimal ami for mine
