### ISSUE TITLE
Questions regarding deployment requirements and "middlebox routing"

### ISSUE THREAD

**Issue by unquietwiki** [AndrewGuenther/fck-nat#74]
Hello again. I decided to try fck-nat with a private VPC subnet range, with its own routing table. However, a test VM I setup could not default route to the fck-nat instance, and forcing the route didn't return any traffic. When digging into this problem, apparently AWS considers this sort of thing a ["middlebox"](https://docs.aws.amazon.com/vpc/latest/userguide/middlebox-routing-console.html), with its own set of routing tables you can propagate, and requires a whole subnet unto itself to work properly.

1. Does this solution require being on its own subnet, separate from other instances?
2. Should we be using the "middlebox" process, if we want to route this stuff correctly?

Thank you for your time.

**Comment by AndrewGuenther** [comment]
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html

Check out this documentation for how to set up NAT instances. Fck-nat follows the same pattern. Effectively you need to route from a "private" (no route to an internet gateway) subnet to a NAT instance in a public subnet (has an internet gateway and the NAT instance gets a public IP).

So I wouldn't say it needs a subnet all to itself, but it does need a subnet separate from your private resources. Does that make sense?

**Comment by unquietwiki** [comment]
That helps, thank you. I'll give it another go this week, as able.

Did you have any thoughts on the "middleware" thing?

**Comment by AndrewGuenther** [comment]
By their definition, I guess a NAT Instance is a "middlebox", but I've never seen those pages in the docs in my life and I'd wager they're going to inject more confusion than answers so I'd stick to the NAT Instance docs which I think provide a good and succinct summary.

**Comment by unquietwiki** [comment]
@AndrewGuenther having those instructions and your advice helped, thank you. It appears having fck-nat on a "public" subnet can successfully NAT requests from a "private" subnet with the routing table set in AWS.
