### ISSUE TITLE
Odd calculation in bandwidth table? 

### ISSUE THREAD

**Issue by jpambrun-vida** [AndrewGuenther/fck-nat#77]
My understanding is that for t3.micro for example, 0.064 Gbps translates to 64 Mbps, not 6.4Mbps ?  

While not amazing, it's ten times more bearable.

https://github.com/AndrewGuenther/fck-nat/blob/5628ea57d04a8dcaff09491b8269f440119d780a/docs/choosing_an_instance_size.md?plain=1#L18-L26

![image](https://github.com/AndrewGuenther/fck-nat/assets/150731165/7f2299ea-35db-4ec3-8fe9-6a3e27a7afb4)

https://docs.aws.amazon.com/ec2/latest/instancetypes/gp.html#gp_network

**Comment by AndrewGuenther** [comment]
Looks like you're right and there was a bug in my script that pulled this info from the API. I'll need to take a closer look at the rest of that page because we reference some of these instance types (t4g.nano in particular) quite a bit from an efficiency standpoint.
