### ISSUE TITLE
Feature Request - Add support for multiple EIPs

### ISSUE THREAD

**Issue by rocktavious** [AndrewGuenther/fck-nat#79]
Following the works of https://github.com/AndrewGuenther/fck-nat/issues/14 and https://github.com/AndrewGuenther/fck-nat/issues/37 and along with using https://github.com/RaJiska/terraform-aws-fck-nat it seems like the fck-nat script doesn't support multiple EIPs.

I have a large interest in making this happen - we are adopting fck-nat at my work and currently fck-nat is a single point of failure even with the HA mode because we require static IP addresses to be assigned.  It appears the code for this - https://github.com/AndrewGuenther/fck-nat/blob/main/service/fck-nat.sh#L17 - is the root problem and if it was adapted to handle multiple EIPs then we could spread the usage of this to our production workloads.

I have used the above Terraform provider to run our copy of fck-nat in our VPC and while the ASG works just fine and the new instance comes up fine what appears to happen is it steals the EIP from the other node.  This leads 1 dead node in the ASG and thus traffic flow gets interrupted.  (if my understanding here doesn't jive correctly please correct me)

So I have a few questions @AndrewGuenther 
1.) Is there a historical reason for not supporting this?
2.) Would you be open to us trying to modify this chunk of the code to support multiple EIPs?
3.) Are there any edgecases or concerns we are not thinking of?

If we can get an agreement going i'd love to spend some of my work cycles on this so we can roll out fck-nat to our production workloads as its already saving us boatloads of money in the places we have rolled it out where a single nat instance is acceptable risk.

Cheers!

**Comment by AndrewGuenther** [comment]
It sounds like you're trying to run fck-nat in an ASG with more than 1 instance, is that correct? If so, that's not going to work. You can only have a default route to a single IP, so you can only be running one instance of fck-nat at a time.

You _can_ improve availability by sharding the IP space across multiple instances, but even then, each node does not have redundancy. This is just a fundamental limitation.

That said, I have a feature I'm working on for fck-nat 2.0 which will allow for failover to a second node more quickly than it happens today: #71 

It's also possible I've misunderstood your question and you're asking something completely different 😅

**Comment by rocktavious** [comment]
@AndrewGuenther - thats exactly right - my concern was that if AWS hardware went bad and we needed to have a 2nd node come up (or even just in the general case were we need to update the AMI version) this would cause a temporary full network outage of traffic flowing which is not acceptable for our main production workloads.  We have some that thats ok to have 5 mins of downtime (and thats currently where fck-nat is used) but a big portion of our traffic flow this is not OK for.

My thinking was that i could have 1 fck-nat in each AZ (in AWS - the ASG would force to spread these out) so that if we needed to roll a node it would only take down 1/3 of our traffic instead of 100%.  Is this not possible with route table rules per private subnet (1 for each AZ)?

**Comment by AndrewGuenther** [comment]
> My thinking was that i could have 1 fck-nat in each AZ (in AWS - the ASG would force to spread these out) so that if we needed to roll a node it would only take down 1/3 of our traffic instead of 100%. Is this not possible with route table rules per private subnet (1 for each AZ)? (this is where we would need the single EC2 bootstrap script to take 1 of the 3 EIPs)

This is absolutely possible. In the `fck-nat-cdk` module, we support passing a list of EIPs which can be used for allocation and each AZ will pull one from the list. I'm not sure how the Terraform module handles it so if you're having issues there that'd be an issue for https://github.com/RaJiska/terraform-aws-fck-nat

**Comment by rocktavious** [comment]
@AndrewGuenther - does the CDK give a different user data script to each instance?  Because the terraform module just sets up a launch configuration so each instance in the ASG gets the same userdata script (maybe i'm reading it wrong or missunderstanding).  So when you look at the code here https://github.com/AndrewGuenther/fck-nat/blob/main/service/fck-nat.sh#L17 - eip_id is only going to be 1 and if you pass multiple i don't think its defined behaviour what the aws cli will do.

What i've seen in my testing is that the next instance that boots up when the ASG is changed from 1 to 2 that new instance takes over the EIP already in use by the existing instance.

**Comment by rocktavious** [comment]
Maybe i'm reading this wrong but unless configure nat is called multiple times the CDK only using 1 EIP - pop 1 off the list and passing only 1 EIP to the fck-nat script.  Which means each instance in the ASG all tries to claim the same EIP.
https://github.com/AndrewGuenther/cdk-fck-nat/blob/main/src/index.ts#L227

...unless the cdk is doing what @lorengordon said above - 1 ASG per AZ.  🤷 i'm not too familiar with the typescript AWS CDK.

**Comment by patrickdk77** [comment]
Yes, you need one ASG per AZ, I dont know if terraform will do the right thing, I used my own script that will convert an existing deployment to this, and I feed it my existing AZ's and the EIPs assigned to them, and my script will kill the remove the EIP, kill the nat, and install a replacement and assign the EIP to the userdata and setup that ASG to manage the instance in that AZ
in my case the userdata contains all the EIP, and it selects the right one based on what AZ it is running in

**Comment by lorengordon** [comment]
Just call the terraform module 3 times! :shrug:

**Comment by AndrewGuenther** [comment]
> unless the cdk is doing what @lorengordon said above - 1 ASG per AZ. 🤷 i'm not too familiar with the typescript AWS CDK.

This is what it is doing. One ASG per AZ. Basically one ASG per "instance" of fck-nat. The configurations are set on the ASG so replacement nodes will have the same config and can take over from stale/old nodes.

**Comment by rocktavious** [comment]
Ok - this all makes sense to me now and I see why supporting multiple EIPs in the script is not helpful.  Thanks all!
