### ISSUE TITLE
t4g.micro pricing is out of date

### ISSUE THREAD

**Issue by lukas-kyeso** [AndrewGuenther/fck-nat#93]
The docs say:
`t4g.nano hourly: $0.0042`

This pricing is out of date. Most regions are at least double this now.

https://aws.amazon.com/ec2/pricing/on-demand/

us-east-2 is 0.0084

Maybe worth adding the AWS pricing page to docs, with a warning to check the up to date pricing yourself

**Comment by AndrewGuenther** [comment]
The docs are correct, it looks like you mixed up `nano` and `micro`

Instance name | On-Demand hourly rate | vCPU | Memory | Storage | Network performance
-- | -- | -- | -- | -- | --
t4g.nano | $0.0042 | 2 | 0.5 GiB | EBS Only | Up to 5 Gigabit
t4g.micro | $0.0084 | 2 | 1 GiB | EBS Only | Up to 5 Gigabit


![image](https://github.com/user-attachments/assets/d828af5f-77fc-4afa-89e9-f657dba052ec)

**Comment by lukas-kyeso** [comment]
Ok I see where I got confused. The CDK instructions (https://fck-nat.dev/stable/deploying/) use micro. The rest use nano.
