### ISSUE TITLE
WebRTC and P2P connection support

### ISSUE THREAD

**Issue by mahadevan-k** [AndrewGuenther/fck-nat#96]
We're facing a problem with establishing WebRTC connections over AWS managed NAT Gateway because it doesn't allow inbound traffic.

Does fck-nat support this? Is it possible to add support if its not available?

**Comment by AndrewGuenther** [comment]
NATs aren't intended to handle inbound traffic. You would either want a load balancer or to expose your services directly to the internet. Handling of inbound connections is out of scope for this project.
